export const criadores = [
	{
		id: 1,
		nome: "Ana Karolina dos Santos do Vale",
		cargo: "Analista de sitemas - RPC",
		descricao: "Experiência em projetos utilizando Next.js, Nest.js, React, Node.js, GraphQL, MongoDB, MySQL, Postgres e Prisma.Contribuí em projetos diversos, participando da construção e manutenção de middleware, APIs REST e GraphQL. Também trabalhei na sustentação de sistemas de vendas, desenvolvimento de interfaces interativas e features de cadastro de serviços.",
		imagem: "https://media.licdn.com/dms/image/v2/D4D03AQHusJ5NBINalQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1706745971311?e=1753920000&v=beta&t=B2CGhfQs5-q3pEoBb56pXWQEhGCky9HWF0dtjEPaswk",
		linkedin: "https://www.linkedin.com/in/kasvrol",
		github: "https://github.com/kasvrol",
		email: "ana.karolina@ufpr.br",
	},
	{
		id: 2,
		nome: "Danielle Arantes",
		cargo: "Analista de Suporte N2 - OmniChat ",
		descricao: "Especialista em Python e Node.js. Trabalho com APIs escaláveis e sistemas distribuídos. Amo aprender novas tecnologias.",
		imagem: "https://media.licdn.com/dms/image/v2/D4D03AQFZjq8mGwetgg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1726233263099?e=1753920000&v=beta&t=3ZCOAcMdQWrWaniQ9AqKefbhrmSRY6FY9tDpGaYKvLI",
		linkedin: "https://www.linkedin.com/in/daniellearantes99/",
		github: "https://github.com/mariaoliveira",
		email: "danielle.arantes8@hotmail.com",
	},
	{
		id: 3,
		nome: "Rafael Hideki Nakamura",
		cargo: "Assitente de TI PL - Grupo Pinho",
		descricao: "Atualmente matriculado no 4° período do curso de Análise e Desenvolvimento de Sistemas (TADS) pela Universidade Federal do Paraná (UFPR), tenho concentrado meus estudos em diversas linguagens, com ênfase em programação orientada a objetos, como Java, e no desenvolvimento web (HTML, CSS e Javascript e Angular 18).\nAo longo de minha trajetória profissional, estou tendo a oportunidade de adentrar no campo da Infraestrutura de TI. Venho aprimorando minhas habilidades em suporte técnico e administração de redes, buscando uma sólida base de conhecimento na área.\nEstou comprometido em continuar desenvolvendo minhas competências técnicas e profissionais, almejando contribuir de forma significativa para o crescimento e sucesso das organizações onde atuo.",
		imagem: "https://media.licdn.com/dms/image/v2/D4D03AQFpbBml8U7a9Q/profile-displayphoto-shrink_200_200/B4DZYA5PwFHwAY-/0/1743771732707?e=1753920000&v=beta&t=KYpJUTPVpVFGkQt5VX5mcX-yio3ySLz1gPZ9y73J_oQ",
		linkedin: "https://www.linkedin.com/in/rafanakamura/",
		github: "https://github.com/carlossouza",
		email: "carlos.souza@email.com",
	},
	{
		id: 4,
		nome: "Nelson Altair Nunes Meduna",
		cargo: "Desenvolvedor Java -Sigraweb",
		descricao: "Atualmente cursando Análise e Desenvolvimento de Sistemas pela UFPR. \nCom 2 anos de experiência em desenvolvimento de software, possuo um histórico de sucesso em projetos de comércio exterior, utilizando tecnologias como Spring Boot, AngularJS, PostgreSQL. Sou apaixonado por desafios técnicos e por criar soluções que impactam positivamente os negócios.",
		imagem: "https://media.licdn.com/dms/image/v2/D4D03AQFnG40CQYTJFQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1710527609252?e=1753920000&v=beta&t=bFDhZ0VUqQ3Mp6qIeCoYOsuR4omEl04O-5PGRqNXd7Q",
		linkedin: "https://www.linkedin.com/in/nelson-meduna/",
		github: "https://github.com/the-nelso",
		email: "nelsonmeduna34@gmail.com",
	},
];
